#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_acc_annoncements:
    path: /login
    controller: App\Controller\MainController::login

account:
    path: /account
    controller: App\Controller\MainController::profile

my_orders:
    path: /my_orders
    controller: App\Controller\MainController::myOrders

offerslist:
    path: /offerslist
    controller: App\Controller\MainController::offersList

offer:
    path: /offer-{id_offer}
    controller: App\Controller\MainController::offer

logout:
    path: /logout
    controller: App\Controller\MainController::logout

my_offers:
    path: /my_offers
    controller: App\Controller\MainController::myOffers

pojedyncza_oferta:
    path: /pojedyncza-oferta
    controller: App\Controller\MainController::pojedynczaOferta
    
offers_to_confirm:
    path: /offers_to_confirm
    controller: App\Controller\MainController::offersToConfirm
    
active_offers:
    path: /active_offers
    controller: App\Controller\MainController::activeOffers
    
users_to_confirm:
    path: /users_to_confirm
    controller: App\Controller\MainController::usersToConfirm

users:
    path: /users
    controller: App\Controller\MainController::users
    
payments:
    path: /payments
    controller: App\Controller\MainController::payments

reservations:
    path: /reservations
    controller: App\Controller\MainController::reservations

confirm_client:
    path: /confirm_client-{id_client}
    controller: App\Controller\MainController::confirmClient

confirm_offer:
    path: /confirm_offer-{id_offer}
    controller: App\Controller\MainController::confirmOffer

delete_offer:
    path: /delete_offer-{id_offer}
    controller: App\Controller\MainController::deleteOffer