<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE4EexdN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE4EexdN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE4EexdN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE4EexdN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerE4EexdN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'E4EexdN',
    'container.build_id' => '5b0b3393',
    'container.build_time' => 1545257713,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerE4EexdN');
