<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxek36q\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxek36q/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKxek36q.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKxek36q\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKxek36q\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Kxek36q',
    'container.build_id' => 'a2d20d4b',
    'container.build_time' => 1544357504,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxek36q');
