<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJsVEu6w\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJsVEu6w/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJsVEu6w.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJsVEu6w\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJsVEu6w\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JsVEu6w',
    'container.build_id' => '398ee981',
    'container.build_time' => 1544281326,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJsVEu6w');
